
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Image image1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label3;

	private global::Gtk.Entry faceEntry;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label4;

	private global::Gtk.Entry eyeEntry;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label5;

	private global::Gtk.Entry smileEntry;

	private global::Gtk.VBox vbox5;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label6;

	private global::Gtk.Entry FColorEntry;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label7;

	private global::Gtk.Entry EColorEntry;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label8;

	private global::Gtk.Entry SColorEntry;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label9;

	private global::Gtk.Entry FLbColorEntry;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Label label10;

	private global::Gtk.Entry ELbColorEntry;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label11;

	private global::Gtk.Entry SLbColorEntry;

	private global::Gtk.Label label2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.WidthRequest = 640;
		this.hbox1.HeightRequest = 480;
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.WidthRequest = 640;
		this.image1.HeightRequest = 480;
		this.image1.Name = "image1";
		this.hbox1.Add(this.image1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 100;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.vbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.vbox1.Add(this.button2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.notebook1.Add(this.hbox1);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Face Detector");
		this.notebook1.SetTabLabel(this.hbox1, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 200;
		this.label3.HeightRequest = 25;
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Face Haar Classifier:");
		this.hbox4.Add(this.label3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.faceEntry = new global::Gtk.Entry();
		this.faceEntry.CanFocus = true;
		this.faceEntry.Name = "faceEntry";
		this.faceEntry.IsEditable = true;
		this.faceEntry.InvisibleChar = '•';
		this.hbox4.Add(this.faceEntry);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.faceEntry]));
		w7.Position = 1;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 200;
		this.label4.HeightRequest = 25;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Eye Haar Classifier:");
		this.hbox5.Add(this.label4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.eyeEntry = new global::Gtk.Entry();
		this.eyeEntry.CanFocus = true;
		this.eyeEntry.Name = "eyeEntry";
		this.eyeEntry.IsEditable = true;
		this.eyeEntry.InvisibleChar = '•';
		this.hbox5.Add(this.eyeEntry);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eyeEntry]));
		w10.Position = 1;
		this.vbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 200;
		this.label5.HeightRequest = 25;
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Smile Haar Classifier:");
		this.hbox6.Add(this.label5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label5]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.smileEntry = new global::Gtk.Entry();
		this.smileEntry.CanFocus = true;
		this.smileEntry.Name = "smileEntry";
		this.smileEntry.IsEditable = true;
		this.smileEntry.InvisibleChar = '•';
		this.hbox6.Add(this.smileEntry);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.smileEntry]));
		w13.Position = 1;
		this.vbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.HeightRequest = 10;
		this.hseparator1.Name = "hseparator1";
		this.vbox5.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.WidthRequest = 200;
		this.label6.HeightRequest = 25;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Face Box Color:");
		this.hbox7.Add(this.label6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.FColorEntry = new global::Gtk.Entry();
		this.FColorEntry.CanFocus = true;
		this.FColorEntry.Name = "FColorEntry";
		this.FColorEntry.IsEditable = true;
		this.FColorEntry.InvisibleChar = '•';
		this.hbox7.Add(this.FColorEntry);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.FColorEntry]));
		w18.Position = 1;
		this.vbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.WidthRequest = 200;
		this.label7.HeightRequest = 25;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Eye Box Color:");
		this.hbox8.Add(this.label7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label7]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.EColorEntry = new global::Gtk.Entry();
		this.EColorEntry.CanFocus = true;
		this.EColorEntry.Name = "EColorEntry";
		this.EColorEntry.IsEditable = true;
		this.EColorEntry.InvisibleChar = '•';
		this.hbox8.Add(this.EColorEntry);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.EColorEntry]));
		w21.Position = 1;
		this.vbox5.Add(this.hbox8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox2.Add(this.vbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.WidthRequest = 200;
		this.label8.HeightRequest = 25;
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Smile Box Color:");
		this.hbox9.Add(this.label8);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label8]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.SColorEntry = new global::Gtk.Entry();
		this.SColorEntry.CanFocus = true;
		this.SColorEntry.Name = "SColorEntry";
		this.SColorEntry.IsEditable = true;
		this.SColorEntry.InvisibleChar = '•';
		this.hbox9.Add(this.SColorEntry);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.SColorEntry]));
		w25.Position = 1;
		this.vbox6.Add(this.hbox9);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.HeightRequest = 10;
		this.hseparator2.Name = "hseparator2";
		this.vbox3.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator2]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.WidthRequest = 200;
		this.label9.HeightRequest = 25;
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Face Label Color:");
		this.hbox10.Add(this.label9);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label9]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.FLbColorEntry = new global::Gtk.Entry();
		this.FLbColorEntry.CanFocus = true;
		this.FLbColorEntry.Name = "FLbColorEntry";
		this.FLbColorEntry.IsEditable = true;
		this.FLbColorEntry.InvisibleChar = '•';
		this.hbox10.Add(this.FLbColorEntry);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.FLbColorEntry]));
		w29.Position = 1;
		this.vbox3.Add(this.hbox10);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox10]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.WidthRequest = 200;
		this.label10.HeightRequest = 25;
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Eye Label Color:");
		this.hbox11.Add(this.label10);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label10]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.ELbColorEntry = new global::Gtk.Entry();
		this.ELbColorEntry.CanFocus = true;
		this.ELbColorEntry.Name = "ELbColorEntry";
		this.ELbColorEntry.IsEditable = true;
		this.ELbColorEntry.InvisibleChar = '•';
		this.hbox11.Add(this.ELbColorEntry);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.ELbColorEntry]));
		w32.Position = 1;
		this.vbox3.Add(this.hbox11);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox11]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox6.Add(this.vbox3);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox3]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.WidthRequest = 200;
		this.label11.HeightRequest = 25;
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Smile Label Color:");
		this.hbox12.Add(this.label11);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label11]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.SLbColorEntry = new global::Gtk.Entry();
		this.SLbColorEntry.CanFocus = true;
		this.SLbColorEntry.Name = "SLbColorEntry";
		this.SLbColorEntry.IsEditable = true;
		this.SLbColorEntry.InvisibleChar = '•';
		this.hbox12.Add(this.SLbColorEntry);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.SLbColorEntry]));
		w36.Position = 1;
		this.vbox7.Add(this.hbox12);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox12]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox6.Add(this.vbox7);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox7]));
		w38.Position = 2;
		this.vbox2.Add(this.vbox6);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox6]));
		w39.Position = 2;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w40 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w40.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Settings");
		this.notebook1.SetTabLabel(this.vbox2, this.label2);
		this.label2.ShowAll();
		this.Add(this.notebook1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 762;
		this.DefaultHeight = 550;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.notebook1.SwitchPage += new global::Gtk.SwitchPageHandler(this.PageSwitch);
		this.button1.Clicked += new global::System.EventHandler(this.startBt);
		this.button2.Clicked += new global::System.EventHandler(this.stopBt);
	}
}
